### ISSUE TITLE
Requiring `other` cases in plural, select, and selectordinal arguments 

### ISSUE THREAD

**Issue by eemeli** [formatjs/intl-messageformat#129]
It would appear that intl-messageformat is not requiring an `other` case in arguments. The original Java implementation [does have](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/SelectFormat.html) this requirement, from where messageformat.js has [adopted it](/SlexAxton/messageformat.js/blob/master/lib/messageformat.js#L389) as well:

> You always have to define a phrase for the default keyword `other`; this phrase is returned when the keyword provided to the `format` method matches no other keyword. If a pattern does not provide a phrase for `other`, the method it's provided to returns the error `U_DEFAULT_KEYWORD_MISSING`.

As a consequence, a source string like `Test {x, select, true{this}}` will compile with intl-messageformat, but not with messageformat.js. This is a problem for migrating from one implementation to the other, as we've now discovered with SlexAxton/messageformat.js#141.

It would be good if we could resolve this discrepancy. How would you feel about introducing a compile-time check for `other` to intl-messageformat, to bring it in line with other ICU MessageFormat implementations?

**Comment by ericf** [comment]
Yeah seems good to me. Not sure when I'll have a chance to get to this though.

**Comment by ggarek** [comment]
I am also interested in this feature, and i would like to help on it. @ericf I may not know how you wish to implement it so i opened a PR with first steps as i see it.

One thing that would be very useful, but may need a bit of refactoring, is the ability to incorporate the original message within the compiler error. I did not find a simple way to do it, because a compiler never gets the original message.

I will be glad to update the PR if you share your vision on how it should be implemented.

**Comment by longlho** [comment]
See #186 for more context
