### ISSUE TITLE
Working with non-stringy data

### ISSUE THREAD

**Issue by syranide** [formatjs/intl-messageformat#86]
Forgive my ignorance... I'm applying this library with React and I really don't see a way to have non-stringy content in a message, but perhaps I've overlooked something (other than splitting a message into multiple pieces, which isn't very manageable/flexible).

Consider perhaps being able to do something like, using $$ to keep the example simple (`<b></b>` is an XML-like primitive exposed by JSX):

```
$$('Hello {countryName}!', {
  countryName: <b>{$$('countryForLanguage')}</b>
});
=> ['Hello ', <b>USA</b>, '!']
```

Or perhaps something more flexible:

```
$$('Hello {countryFunc, call, {USA}}!', {
  countryFunc: name => <b>{name}</b>
});
=> ['Hello ', <b>USA</b>, '!']
```

```
$$('Hello {countryFunc, call, {USA}, {UK}}!', {
  countryFunc: (name1, name2) => <b>{name1} & {name2}</b>
});
=> ['Hello ', <b>USA & UK</b>, '!']
```

**Comment by guncha** [comment]
I'm currently working on a post-processing tool for JSX to automatically extract and transform JsxText tokens into Intl messages and trying to find a way to allow using JSX elements as the substitution values so an example like :

```jsx
const foo = <span>Hello, <strong>{user.name}</strong><span>
```

Would get translated into:

```jsx
const foo = <span>{ i18n("Hello, {exp_543}", {exp_543: <strong>{user.name}</strong>}) }</span>
```

As was mentioned above, this wouldn't work because all arguments are essentially stringified so the example would print `Hello, [Object object]`.

This would work, though, if there was an API to return an array of the formatted contents (strings, numbers or placeholders) before they all get stringified and joined into a single string. So the example would result in `["Hello, ", {type: "strong", props: {children: "Name"}}]` and we could let React take care of converting that to HTML. This way there's no XSS danger and I think the API would be generally nicer to use.

**Comment by syranide** [comment]
@guncha The React elements can be trivially traversed and serialized to whatever format you prefer, so I would suggest that you write this serialization method yourself.

**Comment by tricoder42** [comment]
@guncha That's very similar what I'm doing in [jsLingui](https://github.com/lingui/js-lingui) babel plugins. Feel free to take a look at [test cases](https://github.com/lingui/js-lingui/tree/master/packages/babel-plugin-lingui-transform-react/test/fixtures/component-trans-elements).

I think it should be possible to create custom plugin which does similar transformation, but ends up with react-intl syntax.

**Comment by guncha** [comment]
@tricoder42, thanks for the links - I'm glad someone else has the same idea.

@syranide, can React elements be serialized though? How would you serialize an `onClick` handler? And even if they could, would I then have to parse the resulting string to find the React elements and reconstitute them? Seems like a very roundabout, not to mention expensive, way to achieve the same thing.

Anyway, I briefly looked at the implementation of the `_format` method on the `MessageFormat` class and it basically iterates over the parsed pattern and concatenates the parts to the `result` string. It could just as easily just push the parts into an array and return that.

Then again, after seeing how much `intl-messageformat` does at runtime to parse and compile every single message that's shown to the user, I'm thinking there has to be a better way - i.e., do all that work at compile time.

**Comment by tricoder42** [comment]
@guncha I'll answer your questions if you don't mind, because I've been dealing with this stuff.

> can React elements be serialized though? How would you serialize an onClick handler?

I'm extracting only children of react elements and leaving elements itself in the code. It looks like this:

```js
// Original:
<Trans>Read <a onClick={push('next')}>more.</a></Trans>

// After transformation:
<Trans id="Read <0>more.</0>" components={[<a onClick={push('next')} />]}>
```

The `id` is final `msgId` which is extracted to message catalogs.

Advantages: a) you don't have to update messages and translations after you change element attributes, b) you can use both built-in and custom elements and c) you extract whole phrase in one piece.

Disadvantages: a) you need to cycle through components in runtime and render them, b) it might be confusing to loose element name (although that could be easily fixed).

> Then again, after seeing how much intl-messageformat does at runtime to parse and compile every single message that's shown to the user, I'm thinking there has to be a better way - i.e., do all that work at compile time.

Indeed, message can be parsed and compiled into pure JS function at compile time. The main benefit isn't performance, but bundle size because MessageFormat parser is a huge dependency.
I'm compiling message in [lingui-cli/api/compile.js](https://github.com/lingui/js-lingui/blob/master/packages/lingui-cli/src/api/compile.js). It might need a bit of modification because I'm using `messageformat-parser` instead of `intl-messageformat`, but I think the resulting output should be the same because both libs work with Intl MessageFormat.

**Comment by guncha** [comment]
Thanks a lot for explaining your solution, @tricoder42. I really like the usability of the `Hello <0>world</0>` tags from the perspective of developers and translators. And yes, the re-parsing of the translated string to replace the elements is not great, but this could be addressed by extending the messageformat parser and formatter to handle it. Not sure if my work would approve of using such experiments in production, but it would be an interesting project 😄

**Comment by guncha** [comment]
For anyone interested, I went ahead and forked [intl-messageformat-parser](https://github.com/guncha/intl-messageformat-parser) and [intl-messageformat](https://github.com/guncha/intl-messageformat) to add support for tags as was discussed above. In addition, it's also possible to use object arguments (React elements) for the substitutions.

```jsx
new MessageFormat("{user} made <0>{count, plural, =1 {a comment} other {a few comments}}</0>")
    .formatRaw({
        0: content => <a href="/comments">{content}</a>,
        user: <UserAvatar user={user} />,
        count: 2
    })
// the result is equivalent to =>
[<UserAvatar user={user} />, " made ", <a href="/comments">a few comments</a>]
```

I opted to use a callback for the tags to make this framework agnostic.  The implementation tends to allocate a few more arrays, but otherwise is comparable performance wise. There's no re-parsing of the interpolated results so there's no XSS risk.
